import Header from "../components/Header";
import Hero from "../components/Hero";

export default function HomePage() {
    return (
        <>
            <Header />
            <Hero />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
            Hello there!
            <br />
        </>
    );
}