openapi: '3.0.0'
info:
  version: '1.0.0'
  title: Global Recruits API
  description: The Global Recruits API Specification
servers:
  - url: https://api.globalrecruits.net
    description: Production Environment
tags: 
  - name: mailingList
  - name: discordAuth
security:
  - BearerAuth: [] 

paths:
  /mailinglist:
    post:
      security: [] # No Auth Required
      tags: [ mailingList ]
      operationId: JoinMailingList
      summary: Adds User to Mailing List 
      description: Adds an Email Address to the MailChimp Mailing List
      requestBody: 
        $ref: '#/components/requestBodies/JoinMailingListRequestBody'
      responses:
        201:
          description: Successfully Joined Mailing List
        400:
          $ref: '#/components/responses/ValidationErrorsResponse'
        500:
          $ref: '#/components/responses/MailChimpErrorResponse'
  /auth:
    post:
      security: [] # No Auth Required
      tags: [ discordAuth ]
      operationId: GetDiscordAccessToken
      summary: Retrieves Discord Access Token
      description: Authentication for Discord - Code Exchange/Refresh Token Renewal
      parameters:
        - in: header
          name: X-Authorization-Code
          schema:
            type: string
            example:
              value: "NhhvTDYsFcdgNLnnLijcl7Ku7bEEeee"
        - in: header
          name: X-Refresh-Token
          schema:
            type: string
            example: 
              value: "D43f5y0ahjqew82jZ4NViEr2YafMKhue"
        - in: query
          name: grantType
          required: true
          schema:
            type: string
            enum: [authorization_code, refresh_token]
            example:
              value: "authorization_code"
      responses:
        201:
          $ref: '#/components/responses/GetDiscordAccessTokenResponse'
        400:
          $ref: '#/components/responses/ValidationErrorsResponse'
        401:
          description: Invalid Authorization Code OR Refresh Token Provided
        403: 
          description: Not a Member of the Global Recruits Guild

components:
  requestBodies:
    # POST /mailinglist
    JoinMailingListRequestBody: 
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JoinMailingListRequestBody'
          examples:
            JoinMailingList:
              $ref: '#/components/examples/JoinMailingListRequestBody'

  responses:
    ValidationErrorsResponse:
      description: A Wide-Spread Validation Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorsResponse'
          examples:
            ValidationErrors:
              $ref: '#/components/examples/ValidationErrorsResponse'

    # POST /mailinglist
    MailChimpErrorResponse:
      description: Join Mailing List MailChimp Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            MailChimpError:
              $ref: '#/components/examples/MailChimpErrorResponse'
    
    # POST /auth
    GetDiscordAccessTokenResponse: 
      description: Sucessfully Granted a New Access Token
      content: 
        application/json:
          schema:
            $ref: '#/components/schemas/GetDiscordAccessTokenResponse'
          examples:
            DiscordAccessToken:
              $ref: '#/components/examples/GetDiscordAccessTokenResponse'
            
            
  schemas:
    ValidationErrorsResponse:
      title: ValidationErrorsResponse
      type: array
      minItems: 1
      items: 
        type: object
        title: ValidationError
        required: 
          - title
          - detail
          - pointer
        properties:
          title:
            type: string
          detail: 
            type: string
          pointer:
            type: string

    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        title:
          type: string
        detail: 
          type: string

    # POST /mailinglist
    JoinMailingListRequestBody:
      title: JoinMailingListRequestBody
      type: object
      required: 
        - data
      properties:
        data: 
          type: object
          required:
            - emailAddress
          properties: 
            emailAddress:
              type: string
              format: email
    
    # POST /auth
    GetDiscordAccessTokenResponse:
      title: GetDiscordAccessTokenResponse
      type: object
      required: 
        - access_token
        - token_type
        - expires_in
        - refresh_token
        - scope
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
        refresh_token:
          type: string
        scope:
          type: string

  examples: 
    ValidationErrorsResponse:
      value: [
        {
          title: "VALIDATION_ERROR",
          detail: "must have required property 'emailAddress'",
          pointer: "/data"
        }
      ]

    # POST /mailinglist
    JoinMailingListRequestBody:
      value: {
        data: {
          emailAddress: "contact@globalrecruits.net"
        }
      }
    MailChimpErrorResponse:
      value: {
        title: "Member Exists",
        detail: "contact@globalrecruits.net is already a list member. Use PUT to insert or update list members."
      }
    
    # POST /auth
    GetDiscordAccessTokenResponse:
      value: {
        access_token: "6qrZcUqja7812RVdnEKjpzOL4CvHBFG",
        token_type: "Bearer",
        expires_in: 604800,
        refresh_token: "D43f5y0ahjqew82jZ4NViEr2YafMKhue",
        scope: "identify"
      }

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
